package player;

public enum PlayerType {
	HUMAN,
	RANDOM,
	REACTIVE_AI,
	MEMORY_AI,
	BASIC_PREDICTIVE_AI,
	BASIC_PREDICTIVE_AI_V2,
	HIGH_ROLLER,
	MERCHANT,
	HAND_STATE_CARD_PICKER,
	GENETIC_AI
}
